import { Inter, Oranienbaum } from "next/font/google";
import "./globals.css";
import "../styles/home.css"
import "../styles/products.css"
import "../styles/about.css"
import "../styles/contact.css"
import "../styles/navbar.css"
import "../styles/footer.css"
import "../styles/productscategories.css"
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";

const font = Oranienbaum({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "ISO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div class="navbar-main">
          <Navbar />
        </div>
        {children}
          <Footer />
        </body>
    </html>
  );
}
